install.packages('rjson')
install.packages("shinydashboard")

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("shiny")
BiocManager::install("shinyjs")
BiocManager::install("shinythemes")
BiocManager::install("shinyFiles")
BiocManager::install("shinydashboard")
BiocManager::install("MSnbase")
BiocManager::install("lme4")
BiocManager::install("DT")
BiocManager::install("fdrtool")
BiocManager::install("numDeriv")
BiocManager::install("openxlsx")
BiocManager::install("statmod")
BiocManager::install("svDialogs")
BiocManager::install("statOmics/MSqRob")
